GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/64c8855dab309880248d340d

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/64c8855dab309880248d340d

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test",
    "number": "32423424234234"
}